/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jachst;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Vector;
import javax.imageio.ImageIO;

/**
 *
 * @author stefan.schaufler
 */
public class GUI extends javax.swing.JPanel implements Runnable {

    /**
     * Creates new form GUI
     */
    
     
    Spielfigur F = new Spielfigur(this);
    private static final long serialVersionUID = 1L;
    boolean game_lauft = true;
    
    long delta = 0;
    long last = 0;
    long fps = 0;
    
    Sprite Held;
    Vector<Sprite> actors;
    
    public Steuerung strg;
    
    public GUI() {
        initComponents();
        
        this.setFocusable(true);
        strg = new Steuerung(this);
        initAlleBilder();
        
        
    }
    Held H = new Held(strg,this);
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        strg.initKaesten();
        strg.zeichneAlles(g);
        g.setColor(Color.red);
        g.drawString("FPS: "+Long.toString(fps),20,10);
        
    }
    private BufferedImage[] loadBilder(int bilder){
        /*alleBilder = new BufferedImage[5]; 
        try {
                   alleBilder[0] = ImageIO.read(new File("C:\\Users\\chris\\Desktop\\Planung\\CT-Projekt\\src\\jachst\\bilder\\HeldRechts.jpg"));
               } catch (IOException e) {
                   System.out.println("Es konnte kein Bild gefunden werden.");
               }*/
              
            BufferedImage[] anim = new BufferedImage[bilder];
            BufferedImage source = null;
            
            //URL bild_url = getClass().getClassLoader().getResource(path);
            
            try{
                source = ImageIO.read(new File("bilder/Held.gif"));
            }catch(IOException ioe){ioe.printStackTrace();}
            
            for(int x=0;x<bilder;x++){
                anim[x] = source.getSubimage(x*source.getWidth()/bilder, 0, source.getWidth()/bilder, source.getHeight());        
            }
            
            return anim;
        
    }
    
    private void computeDelta(){
        delta = System.nanoTime() -last;
        last = System.nanoTime();
        
        fps = ((long) 1e9)/delta;
    }
    
    @Override
    public void run() {
        while(game_lauft){
            computeDelta();
            repaint();
            
            try{
                Thread.sleep(10);
            }catch(InterruptedException e){}
        }
        
        
    }
    
    public void initAlleBilder(){
        
        last = System.nanoTime();
        
        actors = new Vector<Sprite>();
        BufferedImage[] held = this.loadBilder(3);
        Held = new Sprite(held,H.pX,H.pY,100,this);
        actors.add(Held);
        
        Thread t = new Thread(this);
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(51, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1000, 500));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
     
       if(evt.getKeyCode() == KeyEvent.VK_RIGHT){
                strg.aendereHeldRichtung(1);           
       }
       if(evt.getKeyCode() == KeyEvent.VK_SPACE){
               
                strg.springenderRolf();
                
                
       }
     
       if(evt.getKeyCode() == KeyEvent.VK_LEFT){
                strg.aendereHeldRichtung(2); 
                
       }
       
       
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_LEFT || evt.getKeyCode() == KeyEvent.VK_RIGHT ){
            strg.aendereHeldRichtung(0);
        }
    }//GEN-LAST:event_formKeyReleased

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
